services:
  edupulse-app:
    build: .
    container_name: edupulse_container
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8501:8501"   # Streamlit
      - "4040:4040"   # Spark Web UI
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    stdin_open: true
    tty: true
    command: streamlit run src/app.py