import pandas as pd
import plotly.express as px
import streamlit as st

from src.dashboard.data import build_good_history_view, normalize_search_id


def render_prediction_guide(student_row=None, gpa_row=None):
    with st.expander("Prediction Guide: What is used and what each term means", expanded=False):
        st.markdown("### Models used")
        st.markdown("- **Risk Prediction**: Random Forest classifier from engagement features.")
        st.markdown("- **GPA Prediction**: Linear regression from engagement features.")

        term_guide = pd.DataFrame([
            {
                "term": "risk_probability",
                "used_by": "Risk model",
                "meaning": "Probability (0 to 1) that a student is at risk (Fail/Withdrawn).",
            },
            {
                "term": "prediction",
                "used_by": "Risk model",
                "meaning": "Predicted risk class (1 = at risk, 0 = not at risk).",
            },
            {
                "term": "total_clicks",
                "used_by": "Risk + GPA models",
                "meaning": "Total VLE interactions (activity volume).",
            },
            {
                "term": "days_active",
                "used_by": "Risk + GPA models",
                "meaning": "Number of active learning days.",
            },
            {
                "term": "engagement_index",
                "used_by": "Risk + GPA models",
                "meaning": "Composite engagement score generated by the engagement pipeline.",
            },
            {
                "term": "predicted_gpa",
                "used_by": "GPA model",
                "meaning": "Displayed GPA percent after bounding to 0-100.",
            },
            {
                "term": "predicted_gpa_raw",
                "used_by": "GPA model",
                "meaning": "Raw linear regression output before bounding.",
            },
            {
                "term": "gpa_bounds_note",
                "used_by": "GPA model",
                "meaning": "Indicates if raw GPA was capped (within_range, capped_to_0, capped_to_100).",
            },
        ])
        st.dataframe(term_guide, use_container_width=True)

        st.markdown("### Why some values are N/A")
        st.markdown("- Student may have no assessment history, so GPA model cannot generate label-based prediction.")
        st.markdown("- Student may be missing required joined records in processed data.")

        if student_row is not None:
            inputs_df = pd.DataFrame([
                {"term": "total_clicks", "value": float(student_row.get("total_clicks", 0))},
                {"term": "days_active", "value": float(student_row.get("days_active", 0))},
                {"term": "engagement_index", "value": float(student_row.get("engagement_index", 0))},
                {"term": "risk_probability", "value": float(student_row.get("risk_probability", 0))},
            ])

            if gpa_row is not None and "predicted_gpa" in gpa_row:
                inputs_df = pd.concat([
                    inputs_df,
                    pd.DataFrame([
                        {"term": "predicted_gpa", "value": float(gpa_row.get("predicted_gpa", 0))},
                        {
                            "term": "predicted_gpa_raw",
                            "value": float(gpa_row.get("predicted_gpa_raw", gpa_row.get("predicted_gpa", 0))),
                        },
                    ]),
                ], ignore_index=True)

            st.markdown("### Inputs used for this student")
            st.dataframe(inputs_df, use_container_width=True)


def render_executive_overview(df_main, df_gpa):
    st.title("Executive Performance Overview")
    render_prediction_guide()

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Students", len(df_main))
    with col2:
        avg_risk = df_main["risk_probability"].mean() * 100
        st.metric("Average Risk Level", f"{avg_risk:.1f}%")
    with col3:
        avg_eng = df_main["engagement_index"].mean()
        st.metric("Avg Engagement", round(avg_eng, 2))
    with col4:
        high_risk_count = len(df_main[df_main["risk_probability"] > 0.7])
        st.metric("High-Risk Alerts", high_risk_count)

    st.markdown("---")

    c_left, c_right = st.columns(2)
    with c_left:
        st.subheader("Student Engagement Distribution")
        fig = px.histogram(df_main, x="engagement_index", nbins=30, color_discrete_sequence=["#4A90E2"])
        st.plotly_chart(fig, use_container_width=True)
    with c_right:
        st.subheader("Student Risk Snapshot")
        threshold_col1, threshold_col2 = st.columns(2)
        with threshold_col1:
            high_risk_threshold = st.slider("High-risk threshold", 0.50, 0.95, 0.70, 0.05)
        with threshold_col2:
            low_risk_threshold = st.slider("Low-risk threshold", 0.05, 0.50, 0.30, 0.05)

        student_count = st.slider("Students per group", 3, 20, 8, 1)

        high_risk_students = df_main[df_main["risk_probability"] >= high_risk_threshold].sort_values(
            by="risk_probability", ascending=False
        ).head(student_count)

        low_risk_students = df_main[df_main["risk_probability"] <= low_risk_threshold].sort_values(
            by="risk_probability", ascending=True
        ).head(student_count)

        high_col, low_col = st.columns(2)
        with high_col:
            st.caption("Highest risk")
            st.dataframe(high_risk_students[["id_student", "engagement_index", "risk_probability"]], use_container_width=True)
        with low_col:
            st.caption("Lowest risk")
            st.dataframe(low_risk_students[["id_student", "engagement_index", "risk_probability"]], use_container_width=True)

    st.markdown("---")
    st.subheader("Good History Students")
    st.caption("Low risk + strong predicted GPA + active participation")
    st.caption("Predicted GPA is bounded to 0-100% for display consistency.")

    if df_gpa is None or df_gpa.empty:
        st.info("GPA prediction data is required for this filter. Run src/regression.py to generate data/processed/gpa_predictions.parquet.")
        return

    if "good_max_risk" not in st.session_state:
        st.session_state["good_max_risk"] = 0.30
    if "good_min_gpa" not in st.session_state:
        st.session_state["good_min_gpa"] = 70
    if "good_min_days" not in st.session_state:
        st.session_state["good_min_days"] = 5

    if st.button("Use Excellent Students Preset"):
        st.session_state["good_max_risk"] = 0.20
        st.session_state["good_min_gpa"] = 75
        st.session_state["good_min_days"] = 7

    f1, f2, f3 = st.columns(3)
    with f1:
        good_max_risk = st.slider("Max risk probability", 0.05, 0.50, step=0.05, key="good_max_risk")
    with f2:
        good_min_gpa = st.slider("Min predicted GPA (%)", 50, 95, step=1, key="good_min_gpa")
    with f3:
        good_min_days = st.slider("Min active days", 1, 30, step=1, key="good_min_days")

    good_history_students = build_good_history_view(
        df_main,
        df_gpa,
        max_risk=good_max_risk,
        min_gpa=good_min_gpa,
        min_days_active=good_min_days,
    )

    st.write(f"Matching students: {len(good_history_students)}")
    st.dataframe(
        good_history_students[["id_student", "risk_probability", "predicted_gpa", "engagement_index", "days_active", "total_clicks"]].head(100),
        use_container_width=True,
    )


def render_student_search(df_main, df_gpa):
    st.title("Student Intelligence Lookup")
    st.markdown("Enter a student ID to retrieve cross-model analysis (Classification and Regression).")

    raw_search_id = st.text_input("Enter Student ID (e.g., 11391):").strip()
    search_id = normalize_search_id(raw_search_id) if raw_search_id else ""

    if not search_id:
        return

    student_row = df_main[df_main["id_student"] == search_id]

    if student_row.empty:
        st.error("Student ID not found. Verify that all Spark pipelines have been executed.")
        return

    res = student_row.iloc[0]
    gpa_row = None

    current_gpa_val = "N/A"
    numeric_gpa = None
    gpa_lookup_status = None
    if df_gpa is not None and not df_gpa.empty and "id_student" in df_gpa.columns:
        gpa_match = df_gpa[df_gpa["id_student"] == search_id]
        if not gpa_match.empty:
            gpa_row = gpa_match.iloc[0]
            numeric_gpa = float(gpa_row["predicted_gpa"])
            current_gpa_val = f"{numeric_gpa:.2f}%"

            bounds_note = str(gpa_row.get("gpa_bounds_note", "within_range"))
            raw_pred = gpa_row.get("predicted_gpa_raw")
            if bounds_note == "capped_to_100":
                st.info(f"Raw model estimate was {float(raw_pred):.2f}%. Displayed value is capped at 100%.")
            elif bounds_note == "capped_to_0":
                st.info(f"Raw model estimate was {float(raw_pred):.2f}%. Displayed value is capped at 0%.")
        else:
            gpa_lookup_status = "missing_for_student"
    elif df_gpa is None:
        st.info("GPA prediction data is not available yet. Run src/regression.py to generate it.")

    st.markdown(f"### Results for Student ID: {search_id}")

    m1, m2, m3, m4 = st.columns(4)
    with m1:
        risk_p = float(res.get("risk_probability", 0))
        st.metric("Risk Probability", f"{risk_p*100:.1f}%")
        st.progress(risk_p)
    with m2:
        st.metric("Predicted GPA", current_gpa_val)
    with m3:
        st.metric("Engagement Index", round(res["engagement_index"], 2))
    with m4:
        st.metric("Activity Level", int(res["total_clicks"]), "Clicks")

    if numeric_gpa is not None:
        if numeric_gpa < 50:
            st.error(f"Critical: Predicted Grade ({current_gpa_val}) is below passing threshold.")
        elif numeric_gpa < 70:
            st.warning(f"Borderline: Predicted Grade ({current_gpa_val}) requires academic support.")
        else:
            st.success(f"Excellent: Predicted Grade ({current_gpa_val}) indicates high performance.")
    elif gpa_lookup_status == "missing_for_student":
        st.info("No GPA prediction exists for this student in gpa_predictions.parquet (likely no assessment history for model training).")

    render_prediction_guide(student_row=res, gpa_row=gpa_row)

    st.markdown("---")

    st.subheader("Student Behavior vs. Class Average")
    comp_df = pd.DataFrame(
        {
            "Metric": ["Engagement", "Total Clicks", "Days Active"],
            "Student": [res["engagement_index"], res["total_clicks"], res["days_active"]],
            "Average": [df_main["engagement_index"].mean(), df_main["total_clicks"].mean(), df_main["days_active"].mean()],
        }
    )
    fig_comp = px.bar(
        comp_df,
        x="Metric",
        y=["Student", "Average"],
        barmode="group",
        color_discrete_map={"Student": "#4A90E2", "Average": "#D3D3D3"},
    )
    st.plotly_chart(fig_comp, use_container_width=True)


def render_institutional_analytics(df_region, df_edu, df_region_gpa, df_edu_gpa):
    st.title("Institutional Performance Analytics")

    if df_region is None or df_edu is None:
        st.warning("Analytics data missing. Run analytics.py to generate regional insights.")
        return

    t1, t2, t3, t4 = st.tabs([
        "Regional Risk",
        "Demographic Risk",
        "Regional GPA Trends",
        "Demographic GPA Trends",
    ])

    with t1:
        st.subheader("Regional Risk vs. Engagement")
        fig_reg = px.scatter(df_region, x="avg_engagement", y="avg_risk", size="student_count", color="region", hover_name="region")
        st.plotly_chart(fig_reg, use_container_width=True)

    with t2:
        st.subheader("Risk Probability by Education Level")
        fig_edu = px.bar(df_edu, x="highest_education", y="avg_risk", color="avg_engagement")
        st.plotly_chart(fig_edu, use_container_width=True)

    with t3:
        st.subheader("Average Predicted GPA by Region")
        if df_region_gpa is not None and not df_region_gpa.empty:
            fig_region_gpa = px.bar(
                df_region_gpa.sort_values("avg_predicted_gpa", ascending=False),
                x="region",
                y="avg_predicted_gpa",
                color="student_count",
            )
            fig_region_gpa.update_layout(yaxis_title="Average Predicted GPA (%)")
            st.plotly_chart(fig_region_gpa, use_container_width=True)
        else:
            st.info("Regional GPA analytics missing. Run analytics.py after regression.py.")

    with t4:
        st.subheader("Average Predicted GPA by Education Level")
        if df_edu_gpa is not None and not df_edu_gpa.empty:
            fig_edu_gpa = px.bar(
                df_edu_gpa.sort_values("avg_predicted_gpa", ascending=False),
                x="highest_education",
                y="avg_predicted_gpa",
                color="student_count",
            )
            fig_edu_gpa.update_layout(yaxis_title="Average Predicted GPA (%)")
            st.plotly_chart(fig_edu_gpa, use_container_width=True)
        else:
            st.info("Demographic GPA analytics missing. Run analytics.py after regression.py.")
